#Importamos la imagen base con python
FROM python:3.12-slim

#Creamos carpeta de trabajo del contenedor
WORKDIR /app

#Copiamos los requerimientos del servidor
COPY requierements.txt .

#Instalamos los requerimientos
RUN pip install --no-cache-dir -r requierements.txt

#Copiar el codigo del API
COPY ./app ./app

#Exponer el puerto del contenedor
EXPOSE 5000

#Coma de ejecucuion FASTAPI
CMD [ "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "5000", "--reload" ]