# Imagen base
FROM python:3.12-slim

# Carpeta de trabajo
WORKDIR /App

# Copiar requirements
COPY requirements.txt .

# Instalar dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Copiar código
COPY ./App ./App

# Exponer puerto
EXPOSE 8000

# Ejecutar FastAPI
CMD ["uvicorn", "App.main:app", "--host", "0.0.0.0", "--port", "8000"]